import{A as b,S,i as E}from"./assets/vendor-4b748348.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&r(u)}).observe(document,{childList:!0,subtree:!0});function s(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(t){if(t.ep)return;t.ep=!0;const n=s(t);fetch(t.href,n)}})();const c=document.querySelector(".mobile-menu"),m=document.querySelector(".open-mobile-menu"),p=document.querySelector(".close-btn-menu"),q=document.querySelectorAll(".mob-menu-link");c&&m&&p?(m.addEventListener("click",()=>{c.classList.add("is-open"),c.classList.remove("is-closed")}),p.addEventListener("click",()=>{c.classList.add("is-closed"),c.classList.remove("is-open")}),window.addEventListener("click",function(e){!c.contains(e.target)&&!m.contains(e.target)&&(c.classList.add("is-closed"),c.classList.remove("is-open"))}),q.forEach(e=>{e.addEventListener("click",()=>{c.classList.add("is-closed"),c.classList.remove("is-open")})})):console.error("Не знайдено всі необхідні елементи");const M=document.querySelector("#js-projects-list"),w=document.querySelector("#js-projects-btn");function A(){let e=0;const o=M.children,s=Array.from(o);if(s.forEach(r=>{e<3&&!r.classList.contains("visible")&&(r.classList.add("visible"),e++)}),s.every(r=>r.classList.contains("visible"))){w.classList.add("hidden");return}}w.addEventListener("click",A);document.addEventListener("DOMContentLoaded",function(){const e=document.querySelector(".accordion-container.faq-list"),o=e.querySelectorAll(".faq-item.ac");if(o.length>0){const s=o[0];s.classList.add("active"),s.querySelector(".faq-text-box.ac-panel").style.display="block"}new b(e,{openOnInit:[0],onOpen:function(s){s.classList.add("active")},onClose:function(s){s.classList.remove("active")}})});const v=document.querySelector("#reviews-list"),y=document.querySelector("#button-prev"),h=document.querySelector("#button-next");let f,d=!0;async function T(){try{const e=await fetch("https://portfolio-js.b.goit.study/api/reviews");if(e.status!=200)throw new Error("Failed to fetch reviews");const o=await e.json();return d=!0,o}catch(e){return E.error({title:"Error",message:"Sorry, something went wrong with reviews."}),e}}function L(){f=window.innerWidth<1280?1:2}function j(e){v.innerHTML=e.map(o=>`
    <li class="swiper-slide">
          <p class="slide-text">${o.review}</p>
          <div class="swiper-user">
            <img
              src="${o.avatar_url}"
              alt="Reviewer"
              class="reviews-image"
              width="40"
              height="40"
              loading="lazy"
            />
            <p class="reviews-name">${o.author}</p>
          </div>
        </li>
    `).join("")}function k(){v.innerHTML='<p class="slide-text error">Not Found</p>'}async function g(){try{const e=await T();j(e);const o=new S(".swiper",{navigation:{nextEl:h,prevEl:y},slidesPerView:f,slidesPerGroup:f,spaceBetween:32,keyboard:{enabled:!0,onlyInViewport:!0,pageUpDown:!0},mousewheel:{sensitivity:1},autoHeight:!1,observer:!0,on:{slideChange:function(){const{isBeginning:s,isEnd:r}=o;y.disabled=s,h.disabled=r}}});d=!0}catch{k(),d=!1}}L();g();window.addEventListener("resize",function(){d&&(L(),g())});const i={input:document.querySelector(".co-work-user"),form:document.querySelector(".co-work-form"),textarea:document.querySelector(".co-work-message"),messageBtn:document.querySelector(".co-work-btn"),modalContainer:document.querySelector(".modal-container")},C=/^\w+(\.\w+)?@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/;function P(e){const o=C.test(e),s=i.input.parentNode,r=s.querySelector(".error-message");if(!o)i.input.classList.add("invalid"),r||O(s,"Please enter a valid email address.");else{i.input.classList.remove("invalid"),r&&r.remove();const t=a({title:"Thank you for your interest in cooperation!",message:"The manager will contact you shortly to discuss further details and opportunities for cooperation. Please stay in touch."});i.modalContainer.insertAdjacentHTML("beforeend",t),document.querySelector("#myModal").classList.add("show"),l()}}i.form.addEventListener("submit",x);function x(e){e.preventDefault();const o=i.input.value,s=i.textarea.value;if(!P(o)){i.input.classList.add("invalid");return}fetch("https://portfolio-js.b.goit.study/api-docs/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:o,message:s})}).then(t=>{if(!t.ok)throw new Error("Network response was not ok");return t.json()}).then(t=>{if(t.success){i.form.reset();const n=a({title:"Thank you for your interest in cooperation!",message:"The manager will contact you shortly to discuss further details and opportunities for cooperation. Please stay in touch."});i.modalContainer.insertAdjacentHTML("beforeend",n),document.querySelector("#myModal").classList.add("show"),l()}else{const n=a({title:"Submission Error",message:t.error||"An error occurred. Please try again later."});i.modalContainer.insertAdjacentHTML("beforeend",n),document.querySelector("#myModal").classList.add("show"),l()}}).catch(t=>{const n=a({title:"Submission Error",message:"An error occurred. Please try again later."});i.modalContainer.insertAdjacentHTML("beforeend",n),document.querySelector("#myModal").classList.add("show"),l()})}function a({title:e,message:o}){return`
      <div id="myModal" class="modal">
        <div class="modal-content">
          <button class="modal-closeBtn"><svg class="modal-closeBtn-icon" width="24" height="24">
          <use href="/CV-L.Jefferson/assets/icon-593cbc5f.svg#icon-close"></use>
          </svg></button>
          <h3 class="modal-title">${e}</h3>
          <p class="modal-message">${o}</p>
        </div>
      </div>
    `}function l(){document.querySelector(".modal-closeBtn").addEventListener("click",H)}function H(){const e=document.querySelector("#myModal");e.classList.remove("show"),e.remove()}function O(e,o){const s=e.querySelector(".error-message"),r=i.input;if(s)s.textContent=o;else{const t=document.createElement("span");t.className="error-message",t.textContent=o,r.insertAdjacentElement("afterend",t)}}
//# sourceMappingURL=commonHelpers.js.map
